version: '3.7'


services:
  database_rentcars:
    image: postgres
    container_name: database_rentcars
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rent
      - POSTGRES_DB=rentcars
    volumes:
      - pgdata:/data/postgres



  app:
    build: .
    container_name: rentcars
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links: 
      - database_rentcars
    depends_on:
      - database_rentcars

volumes: 
  pgdata:
    driver: local
